//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.Findbox.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AS.Findbox.Test.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;ep-theme-cars&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///&lt;title&gt;New Cars, Used Cars, Car Dealers, Prices &amp;amp; Reviews | Cars.com&lt;/title&gt;
        ///
        ///    &lt;meta name=&quot;description&quot; content=&quot;Shop new &amp;amp; used cars, research &amp;amp; compare models, find local dealers/sellers,calculate payments, value your car, sell/trade in your car &amp;amp; more  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarHome {
            get {
                return ResourceManager.GetString("CarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;ep-theme-cars&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///&lt;title data-suffix=&quot; | Cars.com&quot;&gt;New and used Ford E350 Super Duty for Sale Near Me | Cars.com&lt;/title&gt;
        ///
        ///    &lt;meta name=&quot;description&quot; content=&quot;Shop Ford E350 Super Duty vehicles for sale at Cars.com. Research, compare, and save listings, or contact sellers directly from 290  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;section role=&quot;main&quot; class=&quot;sds-page-container&quot; id=&quot;ae-main-content&quot;&gt;
        ///
        ///        &lt;div data-qa=&quot;notifications-are-here&quot;&gt;&lt;/div&gt;
        ///
        ///
        ///
        ///
        ///
        ///
        ///&lt;section class=&quot;sds-page-section session-container&quot;&gt;
        ///  &lt;header class=&quot;sds-page-section__header&quot; role=&quot;presentation&quot;&gt;
        ///    &lt;h1 class=&quot;sds-heading--1 sds-page-section__title&quot;&gt;Sign in&lt;/h1&gt;
        ///  &lt;/header&gt;
        ///
        ///  &lt;div class=&quot;sds-page-section__content&quot;&gt;
        ///
        ///    &lt;div class=&quot;profile-container-with-sidebar&quot;&gt;
        ///      &lt;div class=&quot;column-1&quot;&gt;
        ///
        ///        &lt;p class=&quot;sds-page-section__title-- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SigninPage {
            get {
                return ResourceManager.GetString("SigninPage", resourceCulture);
            }
        }
    }
}
